### ISSUE TITLE
Create consistent save labels for unused decisions

### ISSUE THREAD

**Issue by parevalo** [parevalo/measures_collector#30]
Currently, some labels for which no decision were made as saved as "Decision #" and others are saved as N/A. This is something where @turlejk could help. I can teach you how to do a pull request if you haven't tried that before.

**Comment by turlejk** [comment]
I'm happy to work on this. Currently, I can't find the reason why this happens, but I'll investigate.

Working on this, I could also add some lines of code for reseting the "Decision buttons". There were some issues with some buttons retaining the selected options: 1) if an interpreter changes the decisions at higher level, or 2) decides to skip the sample without saving the interpretation. These would be quick fixes. 

In terms of making the pull requests, I haven't make them yet. I'm new to git and GitHub. I'll check how to do that, but I wouldn't mind if you taught me how to do it.

**Comment by ktarrio** [comment]
Apologies for the late reply -- I don't believe this error occurs, at least not anymore. I'm pretty sure the only inconsistent label was that 'veg type' would write to the spreadsheet when no additional vegetation modifier was added.

**Comment by turlejk** [comment]
There is nothing that could cause the topic issue. However, I fixed the problems with decision buttons that I mentioned in my comment.
